### ISSUE TITLE
Case xxx To zzz

### ISSUE THREAD

**Issue by PELock** [MattDiesel/Ault#5]
Don't be angry Matt, it's from official language specification:

```
#include <MsgBoxConstants.au3>

Local $sMsg = ""

Switch @HOUR
    Case 6 To 11
        $sMsg = "Good Morning"
    Case 12 To 17
        $sMsg = "Good Afternoon"
    Case 18 To 21
        $sMsg = "Good Evening"
    Case Else
        $sMsg = "What are you still doing up?"
EndSwitch

MsgBox($MB_SYSTEMMODAL, "", $sMsg)
```

And another:

```
#include <MsgBoxConstants.au3>

Example()

Func Example()
    Local $sName = InputBox("", "Please enter a word.", "", " M", Default, Default, Default, Default, 10)
    Local $sMsg = ""

    Switch @error
        Case 2
            $sMsg = "Timeout "
            ContinueCase
        Case 1 ; Continuing previous case
            $sMsg &= "Cancellation"
        Case 0
            Switch $sName
                Case "a", "e", "i", "o", "u"
                    $sMsg = "Vowel"
                Case "QP"
                    $sMsg = "Mathematics"
                Case "Q" To "QZ"
                    $sMsg = "Science"
                Case Else
                    $sMsg = "Others"
            EndSwitch
        Case Else
            $sMsg = "Something went horribly wrong."
    EndSwitch

    MsgBox($MB_SYSTEMMODAL, "", $sMsg)
EndFunc   ;==>Example

```

Both throws an unknown error

**Comment by MattDiesel** [comment]
In both cases not implemented. Will look into this, may require an extension to the AST format to get he range working.

**Comment by PELock** [comment]
May I suggest a speed improvement? Why not keep AST branches in Array format not in 1,2,3,4 string list, this has to be splitted everytime, with an Array you have easy access to the counter and each item.

**Comment by MattDiesel** [comment]
Nested arrays are supposed to be very inefficient in AutoIt, and are also
quite tricky to access and create at the moment. Attempts to access out of
range also crashes AutoIt which is not desirable. For example to build a
nested array you must do:

Local $aParent[1] = [0]
Local $aChild[5] - [1,2,3,4,5]
$aParent[0] = $aChild

Then to assign for example, it is not possible to do `$aParent[0][2] = 12`.
There are several open feature requests to make arrays more useful, ranging
from allowing array literals to allowing access/assignment of nested
arrays.

This project was never intended to be high performance, instead I
prioritised how easy it was to read and work with.
