### ISSUE TITLE
Array in Array

### ISSUE THREAD

**Issue by PELock** [MattDiesel/Ault#6]
Another bug from some examples

`Local $aArray_1[1] = ["Data_0"], $iBegin`

It's parsed back to

```
Local $aArray_1[1] = ["Data_0"]
Local $iBegin

```

AutoIt is full of surprises (wish it wouldn't) ;)

**Comment by MattDiesel** [comment]
The two versions are semantically identical, so there is no difference in terms of the meaning of the two. 

There is enough information in the parsed tree to reconstruct it to the original, I'll check if it's possible with the current tree format.

**Comment by PELock** [comment]
Shit sorry, I see it now, I thought it's an AutoIt feature to build array items like this while those are two different declarations.
